CREATE TABLE `salespeople` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR (255) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
) ENGINE=INNODB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
